apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-deployment
  namespace: moganthkumar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dms
  template:
    metadata:
      labels:
        app: dms
    spec:
      serviceAccountName: pod-logs-reader
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
              #  - ip-172-31-20-47   # worker node's hostname(ip)
                - k3s-server  # master node's hostname(ip)
      containers:
      - name: dms-container
        image: moganthkumar/moganth:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: test-volume
          mountPath: /app/logs
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: test-volume
        persistentVolumeClaim:
          claimName: host-pvc