apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dms-ingress
  namespace: moganthkumar
  annotations:
    #kubernetes.io/ingress.class: "nginx" -> not in use anyMore
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx # -> replacement for kubernetes.io/ingress.class: "nginx"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dms-service
            port:
              number: 8000