name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu:latest
    steps:
      - name: Get code into the runner machine (checkout repository)
        uses: actions/checkout@v3
        run: echo "checked out code"

      - name: Check Docker deamon
        run: docker info

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python test_app.py